### ISSUE TITLE
Thea: Token Nomenclature => (Type) Nature Benchmark Token Token symbol us not aligned with its text

### ISSUE THREAD

**Issue by cryptonaz68** [thea-protocol/thea-landingpage#12]
(Type) Nature Benchmark Token Token symbol is not aligned with its text, this might be a resolution issue.
 
<img width="836" alt="Screen Shot 2023-03-27 at 11 56 00 PM" src="https://user-images.githubusercontent.com/113362156/228066110-dc3e51cb-5eb3-423a-877b-3b093a9b236a.png">

**Comment by sudhanshusingh1703** [comment]
Fixed Token symbol alignment on Landing.
